# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_extremephysics', [dirname(__file__)])
        except ImportError:
            import _extremephysics
            return _extremephysics
        if fp is not None:
            try:
                _mod = imp.load_module('_extremephysics', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _extremephysics = swig_import_helper()
    del swig_import_helper
else:
    import _extremephysics
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def ep_version():
  return _extremephysics.ep_version()
ep_version = _extremephysics.ep_version

def ep_set_log_file(*args):
  return _extremephysics.ep_set_log_file(*args)
ep_set_log_file = _extremephysics.ep_set_log_file

def ep_set_show_errors(*args):
  return _extremephysics.ep_set_show_errors(*args)
ep_set_show_errors = _extremephysics.ep_set_show_errors

def ep_message(*args):
  return _extremephysics.ep_message(*args)
ep_message = _extremephysics.ep_message

def ep_print_object_tree():
  return _extremephysics.ep_print_object_tree()
ep_print_object_tree = _extremephysics.ep_print_object_tree

def ep_collision_test_box_box(*args):
  return _extremephysics.ep_collision_test_box_box(*args)
ep_collision_test_box_box = _extremephysics.ep_collision_test_box_box

def ep_collision_test_box_line(*args):
  return _extremephysics.ep_collision_test_box_line(*args)
ep_collision_test_box_line = _extremephysics.ep_collision_test_box_line

def ep_collision_test_box_circle(*args):
  return _extremephysics.ep_collision_test_box_circle(*args)
ep_collision_test_box_circle = _extremephysics.ep_collision_test_box_circle

def ep_collision_test_box_polygon(*args):
  return _extremephysics.ep_collision_test_box_polygon(*args)
ep_collision_test_box_polygon = _extremephysics.ep_collision_test_box_polygon

def ep_collision_test_line_line(*args):
  return _extremephysics.ep_collision_test_line_line(*args)
ep_collision_test_line_line = _extremephysics.ep_collision_test_line_line

def ep_collision_test_line_circle(*args):
  return _extremephysics.ep_collision_test_line_circle(*args)
ep_collision_test_line_circle = _extremephysics.ep_collision_test_line_circle

def ep_collision_test_line_polygon(*args):
  return _extremephysics.ep_collision_test_line_polygon(*args)
ep_collision_test_line_polygon = _extremephysics.ep_collision_test_line_polygon

def ep_collision_test_circle_circle(*args):
  return _extremephysics.ep_collision_test_circle_circle(*args)
ep_collision_test_circle_circle = _extremephysics.ep_collision_test_circle_circle

def ep_collision_test_circle_polygon(*args):
  return _extremephysics.ep_collision_test_circle_polygon(*args)
ep_collision_test_circle_polygon = _extremephysics.ep_collision_test_circle_polygon

def ep_collision_test_polygon_polygon(*args):
  return _extremephysics.ep_collision_test_polygon_polygon(*args)
ep_collision_test_polygon_polygon = _extremephysics.ep_collision_test_polygon_polygon

def ep_ray_cast_box(*args):
  return _extremephysics.ep_ray_cast_box(*args)
ep_ray_cast_box = _extremephysics.ep_ray_cast_box

def ep_ray_cast_line(*args):
  return _extremephysics.ep_ray_cast_line(*args)
ep_ray_cast_line = _extremephysics.ep_ray_cast_line

def ep_ray_cast_circle(*args):
  return _extremephysics.ep_ray_cast_circle(*args)
ep_ray_cast_circle = _extremephysics.ep_ray_cast_circle

def ep_ray_cast_polygon(*args):
  return _extremephysics.ep_ray_cast_polygon(*args)
ep_ray_cast_polygon = _extremephysics.ep_ray_cast_polygon

def ep_first_world():
  return _extremephysics.ep_first_world()
ep_first_world = _extremephysics.ep_first_world

def ep_last_world():
  return _extremephysics.ep_last_world()
ep_last_world = _extremephysics.ep_last_world

def ep_world_create():
  return _extremephysics.ep_world_create()
ep_world_create = _extremephysics.ep_world_create

def ep_world_destroy(*args):
  return _extremephysics.ep_world_destroy(*args)
ep_world_destroy = _extremephysics.ep_world_destroy

def ep_world_exists(*args):
  return _extremephysics.ep_world_exists(*args)
ep_world_exists = _extremephysics.ep_world_exists

def ep_world_clear(*args):
  return _extremephysics.ep_world_clear(*args)
ep_world_clear = _extremephysics.ep_world_clear

def ep_world_set_settings(*args):
  return _extremephysics.ep_world_set_settings(*args)
ep_world_set_settings = _extremephysics.ep_world_set_settings

def ep_world_set_primary_axis(*args):
  return _extremephysics.ep_world_set_primary_axis(*args)
ep_world_set_primary_axis = _extremephysics.ep_world_set_primary_axis

def ep_world_set_sleeping(*args):
  return _extremephysics.ep_world_set_sleeping(*args)
ep_world_set_sleeping = _extremephysics.ep_world_set_sleeping

def ep_world_update_contacts(*args):
  return _extremephysics.ep_world_update_contacts(*args)
ep_world_update_contacts = _extremephysics.ep_world_update_contacts

def ep_world_simulate_step(*args):
  return _extremephysics.ep_world_simulate_step(*args)
ep_world_simulate_step = _extremephysics.ep_world_simulate_step

def ep_world_collision_test_box(*args):
  return _extremephysics.ep_world_collision_test_box(*args)
ep_world_collision_test_box = _extremephysics.ep_world_collision_test_box

def ep_world_collision_test_line(*args):
  return _extremephysics.ep_world_collision_test_line(*args)
ep_world_collision_test_line = _extremephysics.ep_world_collision_test_line

def ep_world_collision_test_circle(*args):
  return _extremephysics.ep_world_collision_test_circle(*args)
ep_world_collision_test_circle = _extremephysics.ep_world_collision_test_circle

def ep_world_collision_test_polygon(*args):
  return _extremephysics.ep_world_collision_test_polygon(*args)
ep_world_collision_test_polygon = _extremephysics.ep_world_collision_test_polygon

def ep_world_ray_cast(*args):
  return _extremephysics.ep_world_ray_cast(*args)
ep_world_ray_cast = _extremephysics.ep_world_ray_cast

def ep_world_get_collision_body(*args):
  return _extremephysics.ep_world_get_collision_body(*args)
ep_world_get_collision_body = _extremephysics.ep_world_get_collision_body

def ep_world_get_collision_shape(*args):
  return _extremephysics.ep_world_get_collision_shape(*args)
ep_world_get_collision_shape = _extremephysics.ep_world_get_collision_shape

def ep_world_multipoly_begin(*args):
  return _extremephysics.ep_world_multipoly_begin(*args)
ep_world_multipoly_begin = _extremephysics.ep_world_multipoly_begin

def ep_world_multipoly_end(*args):
  return _extremephysics.ep_world_multipoly_end(*args)
ep_world_multipoly_end = _extremephysics.ep_world_multipoly_end

def ep_world_multipoly_set_vertex(*args):
  return _extremephysics.ep_world_multipoly_set_vertex(*args)
ep_world_multipoly_set_vertex = _extremephysics.ep_world_multipoly_set_vertex

def ep_world_multipoly_get_first(*args):
  return _extremephysics.ep_world_multipoly_get_first(*args)
ep_world_multipoly_get_first = _extremephysics.ep_world_multipoly_get_first

def ep_world_multipoly_get_last(*args):
  return _extremephysics.ep_world_multipoly_get_last(*args)
ep_world_multipoly_get_last = _extremephysics.ep_world_multipoly_get_last

def ep_world_serialize(*args):
  return _extremephysics.ep_world_serialize(*args)
ep_world_serialize = _extremephysics.ep_world_serialize

def ep_world_unserialize(*args):
  return _extremephysics.ep_world_unserialize(*args)
ep_world_unserialize = _extremephysics.ep_world_unserialize

def ep_world_previous(*args):
  return _extremephysics.ep_world_previous(*args)
ep_world_previous = _extremephysics.ep_world_previous

def ep_world_next(*args):
  return _extremephysics.ep_world_next(*args)
ep_world_next = _extremephysics.ep_world_next

def ep_world_set_uservar(*args):
  return _extremephysics.ep_world_set_uservar(*args)
ep_world_set_uservar = _extremephysics.ep_world_set_uservar

def ep_world_get_uservar(*args):
  return _extremephysics.ep_world_get_uservar(*args)
ep_world_get_uservar = _extremephysics.ep_world_get_uservar

def ep_world_first_polygon(*args):
  return _extremephysics.ep_world_first_polygon(*args)
ep_world_first_polygon = _extremephysics.ep_world_first_polygon

def ep_world_last_polygon(*args):
  return _extremephysics.ep_world_last_polygon(*args)
ep_world_last_polygon = _extremephysics.ep_world_last_polygon

def ep_world_polygon_count(*args):
  return _extremephysics.ep_world_polygon_count(*args)
ep_world_polygon_count = _extremephysics.ep_world_polygon_count

def ep_world_first_body(*args):
  return _extremephysics.ep_world_first_body(*args)
ep_world_first_body = _extremephysics.ep_world_first_body

def ep_world_last_body(*args):
  return _extremephysics.ep_world_last_body(*args)
ep_world_last_body = _extremephysics.ep_world_last_body

def ep_world_body_count(*args):
  return _extremephysics.ep_world_body_count(*args)
ep_world_body_count = _extremephysics.ep_world_body_count

def ep_world_first_contact(*args):
  return _extremephysics.ep_world_first_contact(*args)
ep_world_first_contact = _extremephysics.ep_world_first_contact

def ep_world_last_contact(*args):
  return _extremephysics.ep_world_last_contact(*args)
ep_world_last_contact = _extremephysics.ep_world_last_contact

def ep_world_contact_count(*args):
  return _extremephysics.ep_world_contact_count(*args)
ep_world_contact_count = _extremephysics.ep_world_contact_count

def ep_world_first_hingejoint(*args):
  return _extremephysics.ep_world_first_hingejoint(*args)
ep_world_first_hingejoint = _extremephysics.ep_world_first_hingejoint

def ep_world_last_hingejoint(*args):
  return _extremephysics.ep_world_last_hingejoint(*args)
ep_world_last_hingejoint = _extremephysics.ep_world_last_hingejoint

def ep_world_hingejoint_count(*args):
  return _extremephysics.ep_world_hingejoint_count(*args)
ep_world_hingejoint_count = _extremephysics.ep_world_hingejoint_count

def ep_world_first_distancejoint(*args):
  return _extremephysics.ep_world_first_distancejoint(*args)
ep_world_first_distancejoint = _extremephysics.ep_world_first_distancejoint

def ep_world_last_distancejoint(*args):
  return _extremephysics.ep_world_last_distancejoint(*args)
ep_world_last_distancejoint = _extremephysics.ep_world_last_distancejoint

def ep_world_distancejoint_count(*args):
  return _extremephysics.ep_world_distancejoint_count(*args)
ep_world_distancejoint_count = _extremephysics.ep_world_distancejoint_count

def ep_world_first_railjoint(*args):
  return _extremephysics.ep_world_first_railjoint(*args)
ep_world_first_railjoint = _extremephysics.ep_world_first_railjoint

def ep_world_last_railjoint(*args):
  return _extremephysics.ep_world_last_railjoint(*args)
ep_world_last_railjoint = _extremephysics.ep_world_last_railjoint

def ep_world_railjoint_count(*args):
  return _extremephysics.ep_world_railjoint_count(*args)
ep_world_railjoint_count = _extremephysics.ep_world_railjoint_count

def ep_world_first_sliderjoint(*args):
  return _extremephysics.ep_world_first_sliderjoint(*args)
ep_world_first_sliderjoint = _extremephysics.ep_world_first_sliderjoint

def ep_world_last_sliderjoint(*args):
  return _extremephysics.ep_world_last_sliderjoint(*args)
ep_world_last_sliderjoint = _extremephysics.ep_world_last_sliderjoint

def ep_world_sliderjoint_count(*args):
  return _extremephysics.ep_world_sliderjoint_count(*args)
ep_world_sliderjoint_count = _extremephysics.ep_world_sliderjoint_count

def ep_world_first_view(*args):
  return _extremephysics.ep_world_first_view(*args)
ep_world_first_view = _extremephysics.ep_world_first_view

def ep_world_last_view(*args):
  return _extremephysics.ep_world_last_view(*args)
ep_world_last_view = _extremephysics.ep_world_last_view

def ep_world_view_count(*args):
  return _extremephysics.ep_world_view_count(*args)
ep_world_view_count = _extremephysics.ep_world_view_count

def ep_world_first_water(*args):
  return _extremephysics.ep_world_first_water(*args)
ep_world_first_water = _extremephysics.ep_world_first_water

def ep_world_last_water(*args):
  return _extremephysics.ep_world_last_water(*args)
ep_world_last_water = _extremephysics.ep_world_last_water

def ep_world_water_count(*args):
  return _extremephysics.ep_world_water_count(*args)
ep_world_water_count = _extremephysics.ep_world_water_count

def ep_world_shape_count(*args):
  return _extremephysics.ep_world_shape_count(*args)
ep_world_shape_count = _extremephysics.ep_world_shape_count

def ep_world_force_count(*args):
  return _extremephysics.ep_world_force_count(*args)
ep_world_force_count = _extremephysics.ep_world_force_count

def ep_polygon_create(*args):
  return _extremephysics.ep_polygon_create(*args)
ep_polygon_create = _extremephysics.ep_polygon_create

def ep_polygon_destroy(*args):
  return _extremephysics.ep_polygon_destroy(*args)
ep_polygon_destroy = _extremephysics.ep_polygon_destroy

def ep_polygon_exists(*args):
  return _extremephysics.ep_polygon_exists(*args)
ep_polygon_exists = _extremephysics.ep_polygon_exists

def ep_polygon_set_vertex(*args):
  return _extremephysics.ep_polygon_set_vertex(*args)
ep_polygon_set_vertex = _extremephysics.ep_polygon_set_vertex

def ep_polygon_initialize(*args):
  return _extremephysics.ep_polygon_initialize(*args)
ep_polygon_initialize = _extremephysics.ep_polygon_initialize

def ep_polygon_get_vertex_count(*args):
  return _extremephysics.ep_polygon_get_vertex_count(*args)
ep_polygon_get_vertex_count = _extremephysics.ep_polygon_get_vertex_count

def ep_polygon_get_vertex_x(*args):
  return _extremephysics.ep_polygon_get_vertex_x(*args)
ep_polygon_get_vertex_x = _extremephysics.ep_polygon_get_vertex_x

def ep_polygon_get_vertex_y(*args):
  return _extremephysics.ep_polygon_get_vertex_y(*args)
ep_polygon_get_vertex_y = _extremephysics.ep_polygon_get_vertex_y

def ep_polygon_get_vertex_normal_x(*args):
  return _extremephysics.ep_polygon_get_vertex_normal_x(*args)
ep_polygon_get_vertex_normal_x = _extremephysics.ep_polygon_get_vertex_normal_x

def ep_polygon_get_vertex_normal_y(*args):
  return _extremephysics.ep_polygon_get_vertex_normal_y(*args)
ep_polygon_get_vertex_normal_y = _extremephysics.ep_polygon_get_vertex_normal_y

def ep_polygon_get_edge_length(*args):
  return _extremephysics.ep_polygon_get_edge_length(*args)
ep_polygon_get_edge_length = _extremephysics.ep_polygon_get_edge_length

def ep_polygon_previous(*args):
  return _extremephysics.ep_polygon_previous(*args)
ep_polygon_previous = _extremephysics.ep_polygon_previous

def ep_polygon_next(*args):
  return _extremephysics.ep_polygon_next(*args)
ep_polygon_next = _extremephysics.ep_polygon_next

def ep_polygon_set_uservar(*args):
  return _extremephysics.ep_polygon_set_uservar(*args)
ep_polygon_set_uservar = _extremephysics.ep_polygon_set_uservar

def ep_polygon_get_uservar(*args):
  return _extremephysics.ep_polygon_get_uservar(*args)
ep_polygon_get_uservar = _extremephysics.ep_polygon_get_uservar

def ep_body_create_static(*args):
  return _extremephysics.ep_body_create_static(*args)
ep_body_create_static = _extremephysics.ep_body_create_static

def ep_body_create_dynamic(*args):
  return _extremephysics.ep_body_create_dynamic(*args)
ep_body_create_dynamic = _extremephysics.ep_body_create_dynamic

def ep_body_destroy(*args):
  return _extremephysics.ep_body_destroy(*args)
ep_body_destroy = _extremephysics.ep_body_destroy

def ep_body_exists(*args):
  return _extremephysics.ep_body_exists(*args)
ep_body_exists = _extremephysics.ep_body_exists

def ep_body_get_first_hingejoint(*args):
  return _extremephysics.ep_body_get_first_hingejoint(*args)
ep_body_get_first_hingejoint = _extremephysics.ep_body_get_first_hingejoint

def ep_body_get_last_hingejoint(*args):
  return _extremephysics.ep_body_get_last_hingejoint(*args)
ep_body_get_last_hingejoint = _extremephysics.ep_body_get_last_hingejoint

def ep_body_get_previous_hingejoint(*args):
  return _extremephysics.ep_body_get_previous_hingejoint(*args)
ep_body_get_previous_hingejoint = _extremephysics.ep_body_get_previous_hingejoint

def ep_body_get_next_hingejoint(*args):
  return _extremephysics.ep_body_get_next_hingejoint(*args)
ep_body_get_next_hingejoint = _extremephysics.ep_body_get_next_hingejoint

def ep_body_get_first_distancejoint(*args):
  return _extremephysics.ep_body_get_first_distancejoint(*args)
ep_body_get_first_distancejoint = _extremephysics.ep_body_get_first_distancejoint

def ep_body_get_last_distancejoint(*args):
  return _extremephysics.ep_body_get_last_distancejoint(*args)
ep_body_get_last_distancejoint = _extremephysics.ep_body_get_last_distancejoint

def ep_body_get_previous_distancejoint(*args):
  return _extremephysics.ep_body_get_previous_distancejoint(*args)
ep_body_get_previous_distancejoint = _extremephysics.ep_body_get_previous_distancejoint

def ep_body_get_next_distancejoint(*args):
  return _extremephysics.ep_body_get_next_distancejoint(*args)
ep_body_get_next_distancejoint = _extremephysics.ep_body_get_next_distancejoint

def ep_body_get_first_railjoint(*args):
  return _extremephysics.ep_body_get_first_railjoint(*args)
ep_body_get_first_railjoint = _extremephysics.ep_body_get_first_railjoint

def ep_body_get_last_railjoint(*args):
  return _extremephysics.ep_body_get_last_railjoint(*args)
ep_body_get_last_railjoint = _extremephysics.ep_body_get_last_railjoint

def ep_body_get_previous_railjoint(*args):
  return _extremephysics.ep_body_get_previous_railjoint(*args)
ep_body_get_previous_railjoint = _extremephysics.ep_body_get_previous_railjoint

def ep_body_get_next_railjoint(*args):
  return _extremephysics.ep_body_get_next_railjoint(*args)
ep_body_get_next_railjoint = _extremephysics.ep_body_get_next_railjoint

def ep_body_get_first_sliderjoint(*args):
  return _extremephysics.ep_body_get_first_sliderjoint(*args)
ep_body_get_first_sliderjoint = _extremephysics.ep_body_get_first_sliderjoint

def ep_body_get_last_sliderjoint(*args):
  return _extremephysics.ep_body_get_last_sliderjoint(*args)
ep_body_get_last_sliderjoint = _extremephysics.ep_body_get_last_sliderjoint

def ep_body_get_previous_sliderjoint(*args):
  return _extremephysics.ep_body_get_previous_sliderjoint(*args)
ep_body_get_previous_sliderjoint = _extremephysics.ep_body_get_previous_sliderjoint

def ep_body_get_next_sliderjoint(*args):
  return _extremephysics.ep_body_get_next_sliderjoint(*args)
ep_body_get_next_sliderjoint = _extremephysics.ep_body_get_next_sliderjoint

def ep_body_calculate_mass(*args):
  return _extremephysics.ep_body_calculate_mass(*args)
ep_body_calculate_mass = _extremephysics.ep_body_calculate_mass

def ep_body_set_mass(*args):
  return _extremephysics.ep_body_set_mass(*args)
ep_body_set_mass = _extremephysics.ep_body_set_mass

def ep_body_set_inertia(*args):
  return _extremephysics.ep_body_set_inertia(*args)
ep_body_set_inertia = _extremephysics.ep_body_set_inertia

def ep_body_set_center(*args):
  return _extremephysics.ep_body_set_center(*args)
ep_body_set_center = _extremephysics.ep_body_set_center

def ep_body_set_position(*args):
  return _extremephysics.ep_body_set_position(*args)
ep_body_set_position = _extremephysics.ep_body_set_position

def ep_body_set_position_center(*args):
  return _extremephysics.ep_body_set_position_center(*args)
ep_body_set_position_center = _extremephysics.ep_body_set_position_center

def ep_body_set_position_local_point(*args):
  return _extremephysics.ep_body_set_position_local_point(*args)
ep_body_set_position_local_point = _extremephysics.ep_body_set_position_local_point

def ep_body_set_velocity_center(*args):
  return _extremephysics.ep_body_set_velocity_center(*args)
ep_body_set_velocity_center = _extremephysics.ep_body_set_velocity_center

def ep_body_set_velocity_local_point(*args):
  return _extremephysics.ep_body_set_velocity_local_point(*args)
ep_body_set_velocity_local_point = _extremephysics.ep_body_set_velocity_local_point

def ep_body_set_max_velocity(*args):
  return _extremephysics.ep_body_set_max_velocity(*args)
ep_body_set_max_velocity = _extremephysics.ep_body_set_max_velocity

def ep_body_set_gravity(*args):
  return _extremephysics.ep_body_set_gravity(*args)
ep_body_set_gravity = _extremephysics.ep_body_set_gravity

def ep_body_set_damping(*args):
  return _extremephysics.ep_body_set_damping(*args)
ep_body_set_damping = _extremephysics.ep_body_set_damping

def ep_body_store_impulses(*args):
  return _extremephysics.ep_body_store_impulses(*args)
ep_body_store_impulses = _extremephysics.ep_body_store_impulses

def ep_body_set_sleeping(*args):
  return _extremephysics.ep_body_set_sleeping(*args)
ep_body_set_sleeping = _extremephysics.ep_body_set_sleeping

def ep_body_collision_test_box(*args):
  return _extremephysics.ep_body_collision_test_box(*args)
ep_body_collision_test_box = _extremephysics.ep_body_collision_test_box

def ep_body_collision_test_line(*args):
  return _extremephysics.ep_body_collision_test_line(*args)
ep_body_collision_test_line = _extremephysics.ep_body_collision_test_line

def ep_body_collision_test_circle(*args):
  return _extremephysics.ep_body_collision_test_circle(*args)
ep_body_collision_test_circle = _extremephysics.ep_body_collision_test_circle

def ep_body_collision_test_polygon(*args):
  return _extremephysics.ep_body_collision_test_polygon(*args)
ep_body_collision_test_polygon = _extremephysics.ep_body_collision_test_polygon

def ep_body_ray_cast(*args):
  return _extremephysics.ep_body_ray_cast(*args)
ep_body_ray_cast = _extremephysics.ep_body_ray_cast

def ep_body_apply_impulse(*args):
  return _extremephysics.ep_body_apply_impulse(*args)
ep_body_apply_impulse = _extremephysics.ep_body_apply_impulse

def ep_body_apply_impulse_relative(*args):
  return _extremephysics.ep_body_apply_impulse_relative(*args)
ep_body_apply_impulse_relative = _extremephysics.ep_body_apply_impulse_relative

def ep_body_get_mass(*args):
  return _extremephysics.ep_body_get_mass(*args)
ep_body_get_mass = _extremephysics.ep_body_get_mass

def ep_body_get_inertia(*args):
  return _extremephysics.ep_body_get_inertia(*args)
ep_body_get_inertia = _extremephysics.ep_body_get_inertia

def ep_body_get_center_of_mass_x(*args):
  return _extremephysics.ep_body_get_center_of_mass_x(*args)
ep_body_get_center_of_mass_x = _extremephysics.ep_body_get_center_of_mass_x

def ep_body_get_center_of_mass_y(*args):
  return _extremephysics.ep_body_get_center_of_mass_y(*args)
ep_body_get_center_of_mass_y = _extremephysics.ep_body_get_center_of_mass_y

def ep_body_get_x(*args):
  return _extremephysics.ep_body_get_x(*args)
ep_body_get_x = _extremephysics.ep_body_get_x

def ep_body_get_y(*args):
  return _extremephysics.ep_body_get_y(*args)
ep_body_get_y = _extremephysics.ep_body_get_y

def ep_body_get_x_center(*args):
  return _extremephysics.ep_body_get_x_center(*args)
ep_body_get_x_center = _extremephysics.ep_body_get_x_center

def ep_body_get_y_center(*args):
  return _extremephysics.ep_body_get_y_center(*args)
ep_body_get_y_center = _extremephysics.ep_body_get_y_center

def ep_body_get_rot(*args):
  return _extremephysics.ep_body_get_rot(*args)
ep_body_get_rot = _extremephysics.ep_body_get_rot

def ep_body_get_xvel_center(*args):
  return _extremephysics.ep_body_get_xvel_center(*args)
ep_body_get_xvel_center = _extremephysics.ep_body_get_xvel_center

def ep_body_get_yvel_center(*args):
  return _extremephysics.ep_body_get_yvel_center(*args)
ep_body_get_yvel_center = _extremephysics.ep_body_get_yvel_center

def ep_body_get_xvel_local_point(*args):
  return _extremephysics.ep_body_get_xvel_local_point(*args)
ep_body_get_xvel_local_point = _extremephysics.ep_body_get_xvel_local_point

def ep_body_get_yvel_local_point(*args):
  return _extremephysics.ep_body_get_yvel_local_point(*args)
ep_body_get_yvel_local_point = _extremephysics.ep_body_get_yvel_local_point

def ep_body_get_rotvel(*args):
  return _extremephysics.ep_body_get_rotvel(*args)
ep_body_get_rotvel = _extremephysics.ep_body_get_rotvel

def ep_body_is_static(*args):
  return _extremephysics.ep_body_is_static(*args)
ep_body_is_static = _extremephysics.ep_body_is_static

def ep_body_is_norotation(*args):
  return _extremephysics.ep_body_is_norotation(*args)
ep_body_is_norotation = _extremephysics.ep_body_is_norotation

def ep_body_is_sleeping(*args):
  return _extremephysics.ep_body_is_sleeping(*args)
ep_body_is_sleeping = _extremephysics.ep_body_is_sleeping

def ep_body_stable_timer(*args):
  return _extremephysics.ep_body_stable_timer(*args)
ep_body_stable_timer = _extremephysics.ep_body_stable_timer

def ep_body_out_of_view_timer(*args):
  return _extremephysics.ep_body_out_of_view_timer(*args)
ep_body_out_of_view_timer = _extremephysics.ep_body_out_of_view_timer

def ep_body_coord_local_to_world_x(*args):
  return _extremephysics.ep_body_coord_local_to_world_x(*args)
ep_body_coord_local_to_world_x = _extremephysics.ep_body_coord_local_to_world_x

def ep_body_coord_local_to_world_y(*args):
  return _extremephysics.ep_body_coord_local_to_world_y(*args)
ep_body_coord_local_to_world_y = _extremephysics.ep_body_coord_local_to_world_y

def ep_body_coord_world_to_local_x(*args):
  return _extremephysics.ep_body_coord_world_to_local_x(*args)
ep_body_coord_world_to_local_x = _extremephysics.ep_body_coord_world_to_local_x

def ep_body_coord_world_to_local_y(*args):
  return _extremephysics.ep_body_coord_world_to_local_y(*args)
ep_body_coord_world_to_local_y = _extremephysics.ep_body_coord_world_to_local_y

def ep_body_vect_local_to_world_x(*args):
  return _extremephysics.ep_body_vect_local_to_world_x(*args)
ep_body_vect_local_to_world_x = _extremephysics.ep_body_vect_local_to_world_x

def ep_body_vect_local_to_world_y(*args):
  return _extremephysics.ep_body_vect_local_to_world_y(*args)
ep_body_vect_local_to_world_y = _extremephysics.ep_body_vect_local_to_world_y

def ep_body_vect_world_to_local_x(*args):
  return _extremephysics.ep_body_vect_world_to_local_x(*args)
ep_body_vect_world_to_local_x = _extremephysics.ep_body_vect_world_to_local_x

def ep_body_vect_world_to_local_y(*args):
  return _extremephysics.ep_body_vect_world_to_local_y(*args)
ep_body_vect_world_to_local_y = _extremephysics.ep_body_vect_world_to_local_y

def ep_body_boxchain_begin(*args):
  return _extremephysics.ep_body_boxchain_begin(*args)
ep_body_boxchain_begin = _extremephysics.ep_body_boxchain_begin

def ep_body_boxchain_end(*args):
  return _extremephysics.ep_body_boxchain_end(*args)
ep_body_boxchain_end = _extremephysics.ep_body_boxchain_end

def ep_body_boxchain_set_vertex(*args):
  return _extremephysics.ep_body_boxchain_set_vertex(*args)
ep_body_boxchain_set_vertex = _extremephysics.ep_body_boxchain_set_vertex

def ep_body_boxchain_get_first(*args):
  return _extremephysics.ep_body_boxchain_get_first(*args)
ep_body_boxchain_get_first = _extremephysics.ep_body_boxchain_get_first

def ep_body_boxchain_get_last(*args):
  return _extremephysics.ep_body_boxchain_get_last(*args)
ep_body_boxchain_get_last = _extremephysics.ep_body_boxchain_get_last

def ep_body_previous(*args):
  return _extremephysics.ep_body_previous(*args)
ep_body_previous = _extremephysics.ep_body_previous

def ep_body_next(*args):
  return _extremephysics.ep_body_next(*args)
ep_body_next = _extremephysics.ep_body_next

def ep_body_set_uservar(*args):
  return _extremephysics.ep_body_set_uservar(*args)
ep_body_set_uservar = _extremephysics.ep_body_set_uservar

def ep_body_get_uservar(*args):
  return _extremephysics.ep_body_get_uservar(*args)
ep_body_get_uservar = _extremephysics.ep_body_get_uservar

def ep_body_first_shape(*args):
  return _extremephysics.ep_body_first_shape(*args)
ep_body_first_shape = _extremephysics.ep_body_first_shape

def ep_body_last_shape(*args):
  return _extremephysics.ep_body_last_shape(*args)
ep_body_last_shape = _extremephysics.ep_body_last_shape

def ep_body_shape_count(*args):
  return _extremephysics.ep_body_shape_count(*args)
ep_body_shape_count = _extremephysics.ep_body_shape_count

def ep_body_first_force(*args):
  return _extremephysics.ep_body_first_force(*args)
ep_body_first_force = _extremephysics.ep_body_first_force

def ep_body_last_force(*args):
  return _extremephysics.ep_body_last_force(*args)
ep_body_last_force = _extremephysics.ep_body_last_force

def ep_body_force_count(*args):
  return _extremephysics.ep_body_force_count(*args)
ep_body_force_count = _extremephysics.ep_body_force_count

def ep_contact_destroy(*args):
  return _extremephysics.ep_contact_destroy(*args)
ep_contact_destroy = _extremephysics.ep_contact_destroy

def ep_contact_exists(*args):
  return _extremephysics.ep_contact_exists(*args)
ep_contact_exists = _extremephysics.ep_contact_exists

def ep_contact_get_body1(*args):
  return _extremephysics.ep_contact_get_body1(*args)
ep_contact_get_body1 = _extremephysics.ep_contact_get_body1

def ep_contact_get_body2(*args):
  return _extremephysics.ep_contact_get_body2(*args)
ep_contact_get_body2 = _extremephysics.ep_contact_get_body2

def ep_contact_get_shape1(*args):
  return _extremephysics.ep_contact_get_shape1(*args)
ep_contact_get_shape1 = _extremephysics.ep_contact_get_shape1

def ep_contact_get_shape2(*args):
  return _extremephysics.ep_contact_get_shape2(*args)
ep_contact_get_shape2 = _extremephysics.ep_contact_get_shape2

def ep_contact_get_normal_x(*args):
  return _extremephysics.ep_contact_get_normal_x(*args)
ep_contact_get_normal_x = _extremephysics.ep_contact_get_normal_x

def ep_contact_get_normal_y(*args):
  return _extremephysics.ep_contact_get_normal_y(*args)
ep_contact_get_normal_y = _extremephysics.ep_contact_get_normal_y

def ep_contact_get_point1_active(*args):
  return _extremephysics.ep_contact_get_point1_active(*args)
ep_contact_get_point1_active = _extremephysics.ep_contact_get_point1_active

def ep_contact_get_point2_active(*args):
  return _extremephysics.ep_contact_get_point2_active(*args)
ep_contact_get_point2_active = _extremephysics.ep_contact_get_point2_active

def ep_contact_get_point1_x(*args):
  return _extremephysics.ep_contact_get_point1_x(*args)
ep_contact_get_point1_x = _extremephysics.ep_contact_get_point1_x

def ep_contact_get_point1_y(*args):
  return _extremephysics.ep_contact_get_point1_y(*args)
ep_contact_get_point1_y = _extremephysics.ep_contact_get_point1_y

def ep_contact_get_point2_x(*args):
  return _extremephysics.ep_contact_get_point2_x(*args)
ep_contact_get_point2_x = _extremephysics.ep_contact_get_point2_x

def ep_contact_get_point2_y(*args):
  return _extremephysics.ep_contact_get_point2_y(*args)
ep_contact_get_point2_y = _extremephysics.ep_contact_get_point2_y

def ep_contact_get_point1_separation(*args):
  return _extremephysics.ep_contact_get_point1_separation(*args)
ep_contact_get_point1_separation = _extremephysics.ep_contact_get_point1_separation

def ep_contact_get_point2_separation(*args):
  return _extremephysics.ep_contact_get_point2_separation(*args)
ep_contact_get_point2_separation = _extremephysics.ep_contact_get_point2_separation

def ep_contact_get_point1_normalforce(*args):
  return _extremephysics.ep_contact_get_point1_normalforce(*args)
ep_contact_get_point1_normalforce = _extremephysics.ep_contact_get_point1_normalforce

def ep_contact_get_point1_tangentforce(*args):
  return _extremephysics.ep_contact_get_point1_tangentforce(*args)
ep_contact_get_point1_tangentforce = _extremephysics.ep_contact_get_point1_tangentforce

def ep_contact_get_point2_normalforce(*args):
  return _extremephysics.ep_contact_get_point2_normalforce(*args)
ep_contact_get_point2_normalforce = _extremephysics.ep_contact_get_point2_normalforce

def ep_contact_get_point2_tangentforce(*args):
  return _extremephysics.ep_contact_get_point2_tangentforce(*args)
ep_contact_get_point2_tangentforce = _extremephysics.ep_contact_get_point2_tangentforce

def ep_contact_get_point1_normalveldelta(*args):
  return _extremephysics.ep_contact_get_point1_normalveldelta(*args)
ep_contact_get_point1_normalveldelta = _extremephysics.ep_contact_get_point1_normalveldelta

def ep_contact_get_point1_tangentveldelta(*args):
  return _extremephysics.ep_contact_get_point1_tangentveldelta(*args)
ep_contact_get_point1_tangentveldelta = _extremephysics.ep_contact_get_point1_tangentveldelta

def ep_contact_get_point2_normalveldelta(*args):
  return _extremephysics.ep_contact_get_point2_normalveldelta(*args)
ep_contact_get_point2_normalveldelta = _extremephysics.ep_contact_get_point2_normalveldelta

def ep_contact_get_point2_tangentveldelta(*args):
  return _extremephysics.ep_contact_get_point2_tangentveldelta(*args)
ep_contact_get_point2_tangentveldelta = _extremephysics.ep_contact_get_point2_tangentveldelta

def ep_contact_previous(*args):
  return _extremephysics.ep_contact_previous(*args)
ep_contact_previous = _extremephysics.ep_contact_previous

def ep_contact_next(*args):
  return _extremephysics.ep_contact_next(*args)
ep_contact_next = _extremephysics.ep_contact_next

def ep_hingejoint_create(*args):
  return _extremephysics.ep_hingejoint_create(*args)
ep_hingejoint_create = _extremephysics.ep_hingejoint_create

def ep_hingejoint_destroy(*args):
  return _extremephysics.ep_hingejoint_destroy(*args)
ep_hingejoint_destroy = _extremephysics.ep_hingejoint_destroy

def ep_hingejoint_exists(*args):
  return _extremephysics.ep_hingejoint_exists(*args)
ep_hingejoint_exists = _extremephysics.ep_hingejoint_exists

def ep_hingejoint_set_max_force(*args):
  return _extremephysics.ep_hingejoint_set_max_force(*args)
ep_hingejoint_set_max_force = _extremephysics.ep_hingejoint_set_max_force

def ep_hingejoint_set_motor(*args):
  return _extremephysics.ep_hingejoint_set_motor(*args)
ep_hingejoint_set_motor = _extremephysics.ep_hingejoint_set_motor

def ep_hingejoint_set_limit_settings(*args):
  return _extremephysics.ep_hingejoint_set_limit_settings(*args)
ep_hingejoint_set_limit_settings = _extremephysics.ep_hingejoint_set_limit_settings

def ep_hingejoint_set_lower_limit(*args):
  return _extremephysics.ep_hingejoint_set_lower_limit(*args)
ep_hingejoint_set_lower_limit = _extremephysics.ep_hingejoint_set_lower_limit

def ep_hingejoint_set_upper_limit(*args):
  return _extremephysics.ep_hingejoint_set_upper_limit(*args)
ep_hingejoint_set_upper_limit = _extremephysics.ep_hingejoint_set_upper_limit

def ep_hingejoint_set_lower_spring(*args):
  return _extremephysics.ep_hingejoint_set_lower_spring(*args)
ep_hingejoint_set_lower_spring = _extremephysics.ep_hingejoint_set_lower_spring

def ep_hingejoint_set_upper_spring(*args):
  return _extremephysics.ep_hingejoint_set_upper_spring(*args)
ep_hingejoint_set_upper_spring = _extremephysics.ep_hingejoint_set_upper_spring

def ep_hingejoint_get_body1(*args):
  return _extremephysics.ep_hingejoint_get_body1(*args)
ep_hingejoint_get_body1 = _extremephysics.ep_hingejoint_get_body1

def ep_hingejoint_get_body2(*args):
  return _extremephysics.ep_hingejoint_get_body2(*args)
ep_hingejoint_get_body2 = _extremephysics.ep_hingejoint_get_body2

def ep_hingejoint_get_rotation(*args):
  return _extremephysics.ep_hingejoint_get_rotation(*args)
ep_hingejoint_get_rotation = _extremephysics.ep_hingejoint_get_rotation

def ep_hingejoint_get_xforce(*args):
  return _extremephysics.ep_hingejoint_get_xforce(*args)
ep_hingejoint_get_xforce = _extremephysics.ep_hingejoint_get_xforce

def ep_hingejoint_get_yforce(*args):
  return _extremephysics.ep_hingejoint_get_yforce(*args)
ep_hingejoint_get_yforce = _extremephysics.ep_hingejoint_get_yforce

def ep_hingejoint_get_motor_torque(*args):
  return _extremephysics.ep_hingejoint_get_motor_torque(*args)
ep_hingejoint_get_motor_torque = _extremephysics.ep_hingejoint_get_motor_torque

def ep_hingejoint_get_limit_torque(*args):
  return _extremephysics.ep_hingejoint_get_limit_torque(*args)
ep_hingejoint_get_limit_torque = _extremephysics.ep_hingejoint_get_limit_torque

def ep_hingejoint_previous(*args):
  return _extremephysics.ep_hingejoint_previous(*args)
ep_hingejoint_previous = _extremephysics.ep_hingejoint_previous

def ep_hingejoint_next(*args):
  return _extremephysics.ep_hingejoint_next(*args)
ep_hingejoint_next = _extremephysics.ep_hingejoint_next

def ep_hingejoint_set_uservar(*args):
  return _extremephysics.ep_hingejoint_set_uservar(*args)
ep_hingejoint_set_uservar = _extremephysics.ep_hingejoint_set_uservar

def ep_hingejoint_get_uservar(*args):
  return _extremephysics.ep_hingejoint_get_uservar(*args)
ep_hingejoint_get_uservar = _extremephysics.ep_hingejoint_get_uservar

def ep_distancejoint_create(*args):
  return _extremephysics.ep_distancejoint_create(*args)
ep_distancejoint_create = _extremephysics.ep_distancejoint_create

def ep_distancejoint_destroy(*args):
  return _extremephysics.ep_distancejoint_destroy(*args)
ep_distancejoint_destroy = _extremephysics.ep_distancejoint_destroy

def ep_distancejoint_exists(*args):
  return _extremephysics.ep_distancejoint_exists(*args)
ep_distancejoint_exists = _extremephysics.ep_distancejoint_exists

def ep_distancejoint_set_motor(*args):
  return _extremephysics.ep_distancejoint_set_motor(*args)
ep_distancejoint_set_motor = _extremephysics.ep_distancejoint_set_motor

def ep_distancejoint_set_limit_settings(*args):
  return _extremephysics.ep_distancejoint_set_limit_settings(*args)
ep_distancejoint_set_limit_settings = _extremephysics.ep_distancejoint_set_limit_settings

def ep_distancejoint_set_lower_limit(*args):
  return _extremephysics.ep_distancejoint_set_lower_limit(*args)
ep_distancejoint_set_lower_limit = _extremephysics.ep_distancejoint_set_lower_limit

def ep_distancejoint_set_upper_limit(*args):
  return _extremephysics.ep_distancejoint_set_upper_limit(*args)
ep_distancejoint_set_upper_limit = _extremephysics.ep_distancejoint_set_upper_limit

def ep_distancejoint_set_lower_spring(*args):
  return _extremephysics.ep_distancejoint_set_lower_spring(*args)
ep_distancejoint_set_lower_spring = _extremephysics.ep_distancejoint_set_lower_spring

def ep_distancejoint_set_upper_spring(*args):
  return _extremephysics.ep_distancejoint_set_upper_spring(*args)
ep_distancejoint_set_upper_spring = _extremephysics.ep_distancejoint_set_upper_spring

def ep_distancejoint_get_body1(*args):
  return _extremephysics.ep_distancejoint_get_body1(*args)
ep_distancejoint_get_body1 = _extremephysics.ep_distancejoint_get_body1

def ep_distancejoint_get_body2(*args):
  return _extremephysics.ep_distancejoint_get_body2(*args)
ep_distancejoint_get_body2 = _extremephysics.ep_distancejoint_get_body2

def ep_distancejoint_get_distance(*args):
  return _extremephysics.ep_distancejoint_get_distance(*args)
ep_distancejoint_get_distance = _extremephysics.ep_distancejoint_get_distance

def ep_distancejoint_get_motor_force(*args):
  return _extremephysics.ep_distancejoint_get_motor_force(*args)
ep_distancejoint_get_motor_force = _extremephysics.ep_distancejoint_get_motor_force

def ep_distancejoint_get_limit_force(*args):
  return _extremephysics.ep_distancejoint_get_limit_force(*args)
ep_distancejoint_get_limit_force = _extremephysics.ep_distancejoint_get_limit_force

def ep_distancejoint_previous(*args):
  return _extremephysics.ep_distancejoint_previous(*args)
ep_distancejoint_previous = _extremephysics.ep_distancejoint_previous

def ep_distancejoint_next(*args):
  return _extremephysics.ep_distancejoint_next(*args)
ep_distancejoint_next = _extremephysics.ep_distancejoint_next

def ep_distancejoint_set_uservar(*args):
  return _extremephysics.ep_distancejoint_set_uservar(*args)
ep_distancejoint_set_uservar = _extremephysics.ep_distancejoint_set_uservar

def ep_distancejoint_get_uservar(*args):
  return _extremephysics.ep_distancejoint_get_uservar(*args)
ep_distancejoint_get_uservar = _extremephysics.ep_distancejoint_get_uservar

def ep_railjoint_create(*args):
  return _extremephysics.ep_railjoint_create(*args)
ep_railjoint_create = _extremephysics.ep_railjoint_create

def ep_railjoint_destroy(*args):
  return _extremephysics.ep_railjoint_destroy(*args)
ep_railjoint_destroy = _extremephysics.ep_railjoint_destroy

def ep_railjoint_exists(*args):
  return _extremephysics.ep_railjoint_exists(*args)
ep_railjoint_exists = _extremephysics.ep_railjoint_exists

def ep_railjoint_set_max_normal_force(*args):
  return _extremephysics.ep_railjoint_set_max_normal_force(*args)
ep_railjoint_set_max_normal_force = _extremephysics.ep_railjoint_set_max_normal_force

def ep_railjoint_set_motor(*args):
  return _extremephysics.ep_railjoint_set_motor(*args)
ep_railjoint_set_motor = _extremephysics.ep_railjoint_set_motor

def ep_railjoint_set_limit_settings(*args):
  return _extremephysics.ep_railjoint_set_limit_settings(*args)
ep_railjoint_set_limit_settings = _extremephysics.ep_railjoint_set_limit_settings

def ep_railjoint_set_lower_limit(*args):
  return _extremephysics.ep_railjoint_set_lower_limit(*args)
ep_railjoint_set_lower_limit = _extremephysics.ep_railjoint_set_lower_limit

def ep_railjoint_set_upper_limit(*args):
  return _extremephysics.ep_railjoint_set_upper_limit(*args)
ep_railjoint_set_upper_limit = _extremephysics.ep_railjoint_set_upper_limit

def ep_railjoint_set_lower_spring(*args):
  return _extremephysics.ep_railjoint_set_lower_spring(*args)
ep_railjoint_set_lower_spring = _extremephysics.ep_railjoint_set_lower_spring

def ep_railjoint_set_upper_spring(*args):
  return _extremephysics.ep_railjoint_set_upper_spring(*args)
ep_railjoint_set_upper_spring = _extremephysics.ep_railjoint_set_upper_spring

def ep_railjoint_get_body1(*args):
  return _extremephysics.ep_railjoint_get_body1(*args)
ep_railjoint_get_body1 = _extremephysics.ep_railjoint_get_body1

def ep_railjoint_get_body2(*args):
  return _extremephysics.ep_railjoint_get_body2(*args)
ep_railjoint_get_body2 = _extremephysics.ep_railjoint_get_body2

def ep_railjoint_get_position(*args):
  return _extremephysics.ep_railjoint_get_position(*args)
ep_railjoint_get_position = _extremephysics.ep_railjoint_get_position

def ep_railjoint_get_normal_force(*args):
  return _extremephysics.ep_railjoint_get_normal_force(*args)
ep_railjoint_get_normal_force = _extremephysics.ep_railjoint_get_normal_force

def ep_railjoint_get_motor_force(*args):
  return _extremephysics.ep_railjoint_get_motor_force(*args)
ep_railjoint_get_motor_force = _extremephysics.ep_railjoint_get_motor_force

def ep_railjoint_get_limit_force(*args):
  return _extremephysics.ep_railjoint_get_limit_force(*args)
ep_railjoint_get_limit_force = _extremephysics.ep_railjoint_get_limit_force

def ep_railjoint_previous(*args):
  return _extremephysics.ep_railjoint_previous(*args)
ep_railjoint_previous = _extremephysics.ep_railjoint_previous

def ep_railjoint_next(*args):
  return _extremephysics.ep_railjoint_next(*args)
ep_railjoint_next = _extremephysics.ep_railjoint_next

def ep_railjoint_set_uservar(*args):
  return _extremephysics.ep_railjoint_set_uservar(*args)
ep_railjoint_set_uservar = _extremephysics.ep_railjoint_set_uservar

def ep_railjoint_get_uservar(*args):
  return _extremephysics.ep_railjoint_get_uservar(*args)
ep_railjoint_get_uservar = _extremephysics.ep_railjoint_get_uservar

def ep_sliderjoint_create(*args):
  return _extremephysics.ep_sliderjoint_create(*args)
ep_sliderjoint_create = _extremephysics.ep_sliderjoint_create

def ep_sliderjoint_destroy(*args):
  return _extremephysics.ep_sliderjoint_destroy(*args)
ep_sliderjoint_destroy = _extremephysics.ep_sliderjoint_destroy

def ep_sliderjoint_exists(*args):
  return _extremephysics.ep_sliderjoint_exists(*args)
ep_sliderjoint_exists = _extremephysics.ep_sliderjoint_exists

def ep_sliderjoint_set_max_combined_force(*args):
  return _extremephysics.ep_sliderjoint_set_max_combined_force(*args)
ep_sliderjoint_set_max_combined_force = _extremephysics.ep_sliderjoint_set_max_combined_force

def ep_sliderjoint_set_motor(*args):
  return _extremephysics.ep_sliderjoint_set_motor(*args)
ep_sliderjoint_set_motor = _extremephysics.ep_sliderjoint_set_motor

def ep_sliderjoint_set_limit_settings(*args):
  return _extremephysics.ep_sliderjoint_set_limit_settings(*args)
ep_sliderjoint_set_limit_settings = _extremephysics.ep_sliderjoint_set_limit_settings

def ep_sliderjoint_set_lower_limit(*args):
  return _extremephysics.ep_sliderjoint_set_lower_limit(*args)
ep_sliderjoint_set_lower_limit = _extremephysics.ep_sliderjoint_set_lower_limit

def ep_sliderjoint_set_upper_limit(*args):
  return _extremephysics.ep_sliderjoint_set_upper_limit(*args)
ep_sliderjoint_set_upper_limit = _extremephysics.ep_sliderjoint_set_upper_limit

def ep_sliderjoint_set_lower_spring(*args):
  return _extremephysics.ep_sliderjoint_set_lower_spring(*args)
ep_sliderjoint_set_lower_spring = _extremephysics.ep_sliderjoint_set_lower_spring

def ep_sliderjoint_set_upper_spring(*args):
  return _extremephysics.ep_sliderjoint_set_upper_spring(*args)
ep_sliderjoint_set_upper_spring = _extremephysics.ep_sliderjoint_set_upper_spring

def ep_sliderjoint_get_body1(*args):
  return _extremephysics.ep_sliderjoint_get_body1(*args)
ep_sliderjoint_get_body1 = _extremephysics.ep_sliderjoint_get_body1

def ep_sliderjoint_get_body2(*args):
  return _extremephysics.ep_sliderjoint_get_body2(*args)
ep_sliderjoint_get_body2 = _extremephysics.ep_sliderjoint_get_body2

def ep_sliderjoint_get_position(*args):
  return _extremephysics.ep_sliderjoint_get_position(*args)
ep_sliderjoint_get_position = _extremephysics.ep_sliderjoint_get_position

def ep_sliderjoint_get_normal_force(*args):
  return _extremephysics.ep_sliderjoint_get_normal_force(*args)
ep_sliderjoint_get_normal_force = _extremephysics.ep_sliderjoint_get_normal_force

def ep_sliderjoint_get_torque(*args):
  return _extremephysics.ep_sliderjoint_get_torque(*args)
ep_sliderjoint_get_torque = _extremephysics.ep_sliderjoint_get_torque

def ep_sliderjoint_get_combined_force(*args):
  return _extremephysics.ep_sliderjoint_get_combined_force(*args)
ep_sliderjoint_get_combined_force = _extremephysics.ep_sliderjoint_get_combined_force

def ep_sliderjoint_get_motor_force(*args):
  return _extremephysics.ep_sliderjoint_get_motor_force(*args)
ep_sliderjoint_get_motor_force = _extremephysics.ep_sliderjoint_get_motor_force

def ep_sliderjoint_get_limit_force(*args):
  return _extremephysics.ep_sliderjoint_get_limit_force(*args)
ep_sliderjoint_get_limit_force = _extremephysics.ep_sliderjoint_get_limit_force

def ep_sliderjoint_previous(*args):
  return _extremephysics.ep_sliderjoint_previous(*args)
ep_sliderjoint_previous = _extremephysics.ep_sliderjoint_previous

def ep_sliderjoint_next(*args):
  return _extremephysics.ep_sliderjoint_next(*args)
ep_sliderjoint_next = _extremephysics.ep_sliderjoint_next

def ep_sliderjoint_set_uservar(*args):
  return _extremephysics.ep_sliderjoint_set_uservar(*args)
ep_sliderjoint_set_uservar = _extremephysics.ep_sliderjoint_set_uservar

def ep_sliderjoint_get_uservar(*args):
  return _extremephysics.ep_sliderjoint_get_uservar(*args)
ep_sliderjoint_get_uservar = _extremephysics.ep_sliderjoint_get_uservar

def ep_view_create(*args):
  return _extremephysics.ep_view_create(*args)
ep_view_create = _extremephysics.ep_view_create

def ep_view_destroy(*args):
  return _extremephysics.ep_view_destroy(*args)
ep_view_destroy = _extremephysics.ep_view_destroy

def ep_view_exists(*args):
  return _extremephysics.ep_view_exists(*args)
ep_view_exists = _extremephysics.ep_view_exists

def ep_view_set_rectangle(*args):
  return _extremephysics.ep_view_set_rectangle(*args)
ep_view_set_rectangle = _extremephysics.ep_view_set_rectangle

def ep_view_previous(*args):
  return _extremephysics.ep_view_previous(*args)
ep_view_previous = _extremephysics.ep_view_previous

def ep_view_next(*args):
  return _extremephysics.ep_view_next(*args)
ep_view_next = _extremephysics.ep_view_next

def ep_view_set_uservar(*args):
  return _extremephysics.ep_view_set_uservar(*args)
ep_view_set_uservar = _extremephysics.ep_view_set_uservar

def ep_view_get_uservar(*args):
  return _extremephysics.ep_view_get_uservar(*args)
ep_view_get_uservar = _extremephysics.ep_view_get_uservar

def ep_water_create(*args):
  return _extremephysics.ep_water_create(*args)
ep_water_create = _extremephysics.ep_water_create

def ep_water_destroy(*args):
  return _extremephysics.ep_water_destroy(*args)
ep_water_destroy = _extremephysics.ep_water_destroy

def ep_water_exists(*args):
  return _extremephysics.ep_water_exists(*args)
ep_water_exists = _extremephysics.ep_water_exists

def ep_water_set_parameters(*args):
  return _extremephysics.ep_water_set_parameters(*args)
ep_water_set_parameters = _extremephysics.ep_water_set_parameters

def ep_water_set_rectangle(*args):
  return _extremephysics.ep_water_set_rectangle(*args)
ep_water_set_rectangle = _extremephysics.ep_water_set_rectangle

def ep_water_previous(*args):
  return _extremephysics.ep_water_previous(*args)
ep_water_previous = _extremephysics.ep_water_previous

def ep_water_next(*args):
  return _extremephysics.ep_water_next(*args)
ep_water_next = _extremephysics.ep_water_next

def ep_water_set_uservar(*args):
  return _extremephysics.ep_water_set_uservar(*args)
ep_water_set_uservar = _extremephysics.ep_water_set_uservar

def ep_water_get_uservar(*args):
  return _extremephysics.ep_water_get_uservar(*args)
ep_water_get_uservar = _extremephysics.ep_water_get_uservar

def ep_shape_create_box(*args):
  return _extremephysics.ep_shape_create_box(*args)
ep_shape_create_box = _extremephysics.ep_shape_create_box

def ep_shape_create_line(*args):
  return _extremephysics.ep_shape_create_line(*args)
ep_shape_create_line = _extremephysics.ep_shape_create_line

def ep_shape_create_circle(*args):
  return _extremephysics.ep_shape_create_circle(*args)
ep_shape_create_circle = _extremephysics.ep_shape_create_circle

def ep_shape_create_polygon(*args):
  return _extremephysics.ep_shape_create_polygon(*args)
ep_shape_create_polygon = _extremephysics.ep_shape_create_polygon

def ep_shape_destroy(*args):
  return _extremephysics.ep_shape_destroy(*args)
ep_shape_destroy = _extremephysics.ep_shape_destroy

def ep_shape_exists(*args):
  return _extremephysics.ep_shape_exists(*args)
ep_shape_exists = _extremephysics.ep_shape_exists

def ep_shape_get_first_contact(*args):
  return _extremephysics.ep_shape_get_first_contact(*args)
ep_shape_get_first_contact = _extremephysics.ep_shape_get_first_contact

def ep_shape_get_last_contact(*args):
  return _extremephysics.ep_shape_get_last_contact(*args)
ep_shape_get_last_contact = _extremephysics.ep_shape_get_last_contact

def ep_shape_get_previous_contact(*args):
  return _extremephysics.ep_shape_get_previous_contact(*args)
ep_shape_get_previous_contact = _extremephysics.ep_shape_get_previous_contact

def ep_shape_get_next_contact(*args):
  return _extremephysics.ep_shape_get_next_contact(*args)
ep_shape_get_next_contact = _extremephysics.ep_shape_get_next_contact

def ep_shape_set_material(*args):
  return _extremephysics.ep_shape_set_material(*args)
ep_shape_set_material = _extremephysics.ep_shape_set_material

def ep_shape_set_collision(*args):
  return _extremephysics.ep_shape_set_collision(*args)
ep_shape_set_collision = _extremephysics.ep_shape_set_collision

def ep_shape_collision_test_box(*args):
  return _extremephysics.ep_shape_collision_test_box(*args)
ep_shape_collision_test_box = _extremephysics.ep_shape_collision_test_box

def ep_shape_collision_test_line(*args):
  return _extremephysics.ep_shape_collision_test_line(*args)
ep_shape_collision_test_line = _extremephysics.ep_shape_collision_test_line

def ep_shape_collision_test_circle(*args):
  return _extremephysics.ep_shape_collision_test_circle(*args)
ep_shape_collision_test_circle = _extremephysics.ep_shape_collision_test_circle

def ep_shape_collision_test_polygon(*args):
  return _extremephysics.ep_shape_collision_test_polygon(*args)
ep_shape_collision_test_polygon = _extremephysics.ep_shape_collision_test_polygon

def ep_shape_ray_cast(*args):
  return _extremephysics.ep_shape_ray_cast(*args)
ep_shape_ray_cast = _extremephysics.ep_shape_ray_cast

def ep_shape_previous(*args):
  return _extremephysics.ep_shape_previous(*args)
ep_shape_previous = _extremephysics.ep_shape_previous

def ep_shape_next(*args):
  return _extremephysics.ep_shape_next(*args)
ep_shape_next = _extremephysics.ep_shape_next

def ep_shape_set_uservar(*args):
  return _extremephysics.ep_shape_set_uservar(*args)
ep_shape_set_uservar = _extremephysics.ep_shape_set_uservar

def ep_shape_get_uservar(*args):
  return _extremephysics.ep_shape_get_uservar(*args)
ep_shape_get_uservar = _extremephysics.ep_shape_get_uservar

def ep_force_create(*args):
  return _extremephysics.ep_force_create(*args)
ep_force_create = _extremephysics.ep_force_create

def ep_force_destroy(*args):
  return _extremephysics.ep_force_destroy(*args)
ep_force_destroy = _extremephysics.ep_force_destroy

def ep_force_exists(*args):
  return _extremephysics.ep_force_exists(*args)
ep_force_exists = _extremephysics.ep_force_exists

def ep_force_set_force(*args):
  return _extremephysics.ep_force_set_force(*args)
ep_force_set_force = _extremephysics.ep_force_set_force

def ep_force_previous(*args):
  return _extremephysics.ep_force_previous(*args)
ep_force_previous = _extremephysics.ep_force_previous

def ep_force_next(*args):
  return _extremephysics.ep_force_next(*args)
ep_force_next = _extremephysics.ep_force_next

def ep_force_set_uservar(*args):
  return _extremephysics.ep_force_set_uservar(*args)
ep_force_set_uservar = _extremephysics.ep_force_set_uservar

def ep_force_get_uservar(*args):
  return _extremephysics.ep_force_get_uservar(*args)
ep_force_get_uservar = _extremephysics.ep_force_get_uservar
# This file is compatible with both classic and new-style classes.


